// <auto-generated />
using FourtitudeAspNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FourtitudeAspNet.Migrations
{
    [DbContext(typeof(FourtitudeDbContext))]
    [Migration("20251104174932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FourtitudeAspNet.Models.Partner", b =>
                {
                    b.Property<string>("PartnerKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerKey");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            PartnerKey = "FG-00001",
                            PartnerName = "FAKEGOOGLE",
                            Password = "FAKEPASSWORD1234"
                        },
                        new
                        {
                            PartnerKey = "FG-00002",
                            PartnerName = "FAKEPEOPLE",
                            Password = "FAKEPASSWORD4578"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
